"""Server-side source of truth for tenant rent charge amounts.

Client payloads are display/input hints only. Financial charge amounts come from
``rental_payments`` invoices generated by ``rent_payment_cron``.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

CHARGEABLE_STATUSES = frozenset({"pending", "late", "partial"})
SETTLED_STATUSES = frozenset({"paid", "completed"})
NON_CHARGEABLE_STATUSES = frozenset({"cancelled", "canceled"})


def period_query(contract_id: Any, period_start: datetime) -> dict:
    """Mongo query matching all supported encodings of one lease month."""
    return {
        "contract_id": str(contract_id),
        "record_type": {"$ne": "checkout_attempt"},
        "invoice_id": {"$exists": False},
        "$or": [
            {"period": period_start.strftime("%Y-%m")},
            {"period_year": period_start.year, "period_month_num": period_start.month},
            {"period_year": period_start.year, "period_month": period_start.strftime("%B")},
        ],
    }


def current_period_query(contract_id: Any, now: datetime | None = None) -> dict:
    """Compatibility wrapper for callers charging the current month."""
    return period_query(contract_id, now or datetime.now(timezone.utc))


def _status_query(base: dict, statuses) -> dict:
    return {**base, "status": {"$in": list(statuses)}}


def invoice_balance(invoice: dict) -> dict:
    """Return normalized invoice financials without trusting client values.

    ``amount`` is base rent, ``late_fee`` is the server-applied fee,
    ``total_due`` is the authoritative gross due when present, and
    ``total_paid`` represents prior partial payments.
    """
    status = str(invoice.get("status") or "").lower()
    amount = max(float(invoice.get("amount") or 0), 0.0)
    late_fee = max(float(invoice.get("late_fee") or 0), 0.0)
    total_due = max(float(invoice.get("total_due") or (amount + late_fee)), 0.0)
    total_paid = max(float(invoice.get("total_paid") or 0), 0.0)

    # Fail closed: only explicitly chargeable invoice states expose a balance.
    outstanding = 0.0
    if status in CHARGEABLE_STATUSES:
        outstanding = max(total_due - total_paid, 0.0)

    return {
        "status": status,
        "amount": round(amount, 2),
        "late_fee": round(late_fee, 2),
        "total_due": round(total_due, 2),
        "total_paid": round(total_paid, 2),
        "outstanding": round(outstanding, 2),
    }


async def _find_period_invoice(db, contract_id: Any, period_start: datetime) -> dict | None:
    base = period_query(contract_id, period_start)

    # A successful payment for the period wins over any stale pending duplicate.
    settled = await db.rental_payments.find_one(_status_query(base, SETTLED_STATUSES))
    if settled is not None:
        return settled

    return await db.rental_payments.find_one(_status_query(base, CHARGEABLE_STATUSES))


async def resolve_period_rent_charge(db, contract: dict, period_start: datetime) -> dict:
    """Ensure/read an authoritative charge for an explicit lease month."""
    if period_start.tzinfo is None:
        period_start = period_start.replace(tzinfo=timezone.utc)
    period_start = period_start.astimezone(timezone.utc).replace(
        day=1, hour=0, minute=0, second=0, microsecond=0
    )
    invoice = await _find_period_invoice(db, contract.get("_id"), period_start)
    if invoice is None:
        from .rent_payment_cron import ensure_period_payment
        result, invoice = await ensure_period_payment(
            db, contract, period_start,
            apply_late_fee=(period_start.year, period_start.month) ==
                           (datetime.now(timezone.utc).year, datetime.now(timezone.utc).month),
        )
        if result.startswith("skip_"):
            raise ValueError(f"rent invoice unavailable: {result}")
        invoice = invoice or await _find_period_invoice(db, contract.get("_id"), period_start)
    if invoice is None:
        raise RuntimeError("rent invoice is not in a chargeable state")
    balance = invoice_balance(invoice)
    return {"invoice": invoice, "invoice_id": str(invoice.get("_id", "")),
            "period": period_start.strftime("%Y-%m"), **balance}


async def resolve_current_rent_charge(db, contract: dict, now: datetime | None = None) -> dict:
    """Ensure/read the current invoice and return its server-side charge snapshot.

    If the cron has not created the invoice yet, reuse its existing idempotent
    generator instead of inventing a second late-fee or due-date calculation.
    Paid/completed records are checked first so stale pending duplicates cannot
    cause a second charge for the same period.
    """
    now = now or datetime.now(timezone.utc)
    return await resolve_period_rent_charge(db, contract, now)
