"""Server-side source of truth for tenant rent charge amounts.

Client payloads are display/input hints only. Financial charge amounts come from
``rental_payments`` invoices generated by ``rent_payment_cron``.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

CHARGEABLE_STATUSES = frozenset({"pending", "late", "partial"})
SETTLED_STATUSES = frozenset({"paid", "completed"})
NON_CHARGEABLE_STATUSES = frozenset({"cancelled", "canceled"})


def current_period_query(contract_id: Any, now: datetime | None = None) -> dict:
    """Mongo query matching all period encodings used by the rent cron."""
    now = now or datetime.now(timezone.utc)
    return {
        "contract_id": str(contract_id),
        "$or": [
            {"period": now.strftime("%Y-%m")},
            {"period_year": now.year, "period_month_num": now.month},
            {"period_year": now.year, "period_month": now.strftime("%B")},
        ],
    }


def _status_query(base: dict, statuses) -> dict:
    return {**base, "status": {"$in": list(statuses)}}


def invoice_balance(invoice: dict) -> dict:
    """Return normalized invoice financials without trusting client values.

    ``amount`` is base rent, ``late_fee`` is the server-applied fee,
    ``total_due`` is the authoritative gross due when present, and
    ``total_paid`` represents prior partial payments.
    """
    status = str(invoice.get("status") or "").lower()
    amount = max(float(invoice.get("amount") or 0), 0.0)
    late_fee = max(float(invoice.get("late_fee") or 0), 0.0)
    total_due = max(float(invoice.get("total_due") or (amount + late_fee)), 0.0)
    total_paid = max(float(invoice.get("total_paid") or 0), 0.0)

    # Fail closed: only explicitly chargeable invoice states expose a balance.
    outstanding = 0.0
    if status in CHARGEABLE_STATUSES:
        outstanding = max(total_due - total_paid, 0.0)

    return {
        "status": status,
        "amount": round(amount, 2),
        "late_fee": round(late_fee, 2),
        "total_due": round(total_due, 2),
        "total_paid": round(total_paid, 2),
        "outstanding": round(outstanding, 2),
    }


async def _find_current_invoice(db, contract_id: Any, now: datetime) -> dict | None:
    base = current_period_query(contract_id, now)

    # A successful payment for the period wins over any stale pending duplicate.
    settled = await db.rental_payments.find_one(_status_query(base, SETTLED_STATUSES))
    if settled is not None:
        return settled

    return await db.rental_payments.find_one(_status_query(base, CHARGEABLE_STATUSES))


async def resolve_current_rent_charge(db, contract: dict, now: datetime | None = None) -> dict:
    """Ensure/read the current invoice and return its server-side charge snapshot.

    If the cron has not created the invoice yet, reuse its existing idempotent
    generator instead of inventing a second late-fee or due-date calculation.
    Paid/completed records are checked first so stale pending duplicates cannot
    cause a second charge for the same period.
    """
    now = now or datetime.now(timezone.utc)
    invoice = await _find_current_invoice(db, contract.get("_id"), now)

    if invoice is None:
        from .rent_payment_cron import ensure_current_period_payment

        result = await ensure_current_period_payment(db, contract)
        if result.startswith("skip_"):
            raise ValueError(f"current rent invoice unavailable: {result}")
        invoice = await _find_current_invoice(db, contract.get("_id"), now)

    if invoice is None:
        # Existing cancelled/unknown-state documents are intentionally not
        # converted into a charge. Manual reconciliation is safer than billing.
        raise RuntimeError("current rent invoice is not in a chargeable state")

    balance = invoice_balance(invoice)
    return {
        "invoice": invoice,
        "invoice_id": str(invoice.get("_id", "")),
        **balance,
    }
